### ISSUE TITLE
Unexpected test success Tests.Validation.Theorems.Interchange

### ISSUE THREAD

**Issue by danwdart** [snowleopard/selective#59] opened 2022-12-16 12:58 UTC
Hello, I get an unexpected test success when trying to compile selective 0.5 using ghc 9.4.

OK (expected failure): Tests.Validation.Theorems.(f <*> g) == (f `apS` g)

Unexpected test success:
    Tests.Validation.Theorems.Interchange: (x *> (y <*? z)) == ((x *> y) <*? z)

Has anyone got any idea there?

Thanks

**Comment by snowleopard** [comment] 2022-12-17 04:25
This seems like a duplicate of #48. We fixed that but it looks like you're using an old version 0.5, which is missing the fix.

**Comment by snowleopard** [comment] 2022-12-17 04:26
Ah, wait, it looks like we never released a newer version! I'll do that.

**Comment by danwdart** [comment] 2022-12-20 13:26
Hah, super. Thanks!

**Comment by snowleopard** [comment] 2023-02-19 06:06
Done: https://hackage.haskell.org/package/selective-0.6. Apologies for taking so long.

**Closed by snowleopard** 2023-02-19 06:06 UTC
